import { prisma } from '@awb/database'
import { requireAdmin } from '@/lib/tenancy'
import { AppShell } from '@/components/account/app-shell'
import { ActionForm } from '@/components/account/action-form'
import { savePlan, attachPlanPrice, createPlanPrice } from '@/app/actions/admin'
import { money } from '@/lib/billing/access'
import { stripeReady } from '@/lib/billing/stripe'
export default async function AdminPlansPage() {
  await requireAdmin()
  const plans = await prisma.billingPlan.findMany({ orderBy: { position: 'asc' }, include: { prices: { where: { active: true } }, _count: { select: { workspaces: true } } } })
  return <AppShell title="Package management" active="/admin/plans"><div className="wt-heading"><p className="wt-eyebrow">PLATFORM ADMIN</p><h1>Packages that grow with you.</h1><p>Manage names, website allowances, features and monthly or yearly pricing.</p></div>{!stripeReady() && <div className="wt-notice">Stripe is not connected. Plan details can be edited now; pricing and checkout become available after configuration.</div>}<div className="wt-two-col">{plans.map(plan => <section className="wt-card" key={plan.id}><div className="wt-card-heading"><h2>{plan.name}</h2><span className="wt-badge">{plan._count.workspaces} workspaces</span></div><ActionForm action={savePlan} label="Save package"><input type="hidden" name="id" value={plan.id} /><div className="wt-two-col"><label>Package name<input name="name" defaultValue={plan.name} required maxLength={80} /></label><label>Website limit<input name="websiteLimit" type="number" min={1} max={100000} required defaultValue={plan.websiteLimit} /></label></div><label>Description<input name="description" required minLength={5} maxLength={300} defaultValue={plan.description} /></label><label>Features · one per line<textarea name="features" rows={3} defaultValue={plan.features.join('\n')} /></label><label className="wt-checkbox"><input type="checkbox" name="active" defaultChecked={plan.active} />Visible for new purchases</label></ActionForm><div className="wt-divider" /><h3>Pricing</h3>{plan.prices.length ? plan.prices.map(price => <p className="wt-price-row" key={price.id}>{money(price.amount, price.currency)} {price.currency.toUpperCase()} / {price.interval}<small>{price.stripePriceId}</small></p>) : <p className="wt-muted">No price configured. Checkout stays unavailable.</p>}<ActionForm action={createPlanPrice} label="Create price in Stripe" disabled={!stripeReady()}><input type="hidden" name="planId" value={plan.id} /><div className="wt-three-col"><label>Amount<input type="number" name="amount" min="0.50" step="0.01" required placeholder="29.00" /></label><label>Currency<select name="currency"><option value="cad">CAD</option><option value="usd">USD</option><option value="eur">EUR</option><option value="gbp">GBP</option><option value="aud">AUD</option></select></label><label>Period<select name="interval"><option value="month">Monthly</option><option value="year">Yearly</option></select></label></div><small>Creates a new price for future purchases. Existing subscribers keep their current price.</small></ActionForm><details className="mt-4"><summary>Use an existing Stripe price</summary><ActionForm action={attachPlanPrice} label="Verify and attach price" disabled={!stripeReady()}><input type="hidden" name="planId" value={plan.id} /><label>Stripe price ID<input name="stripePriceId" required placeholder="price_…" /></label></ActionForm></details></section>)}</div></AppShell>
}
