import { Children, isValidElement, useId, type ReactNode } from 'react'
import { BalancedGrid } from '../balanced-grid'
import { z } from 'zod'
import { defineComponent } from '../types'
import { Container, Cta, Heading, Media, Prose, Section } from '../primitives'
import { cardColor, elementColor } from '../element-colors'
import { imageSizing } from '../image-sizing'

const safeLink = z.string().max(2000).default('').refine(value => !value || /^\/(?!\/)/.test(value) || /^#[\w-]+$/.test(value) || /^https?:\/\//i.test(value), 'Use a page path or HTTP(S) link')
const portfolioProps = z.object({
  eyebrow: z.string().default('Selected work'), heading: z.string().default('Products and projects worth exploring'), intro: z.string().default(''),
  layout: z.enum(['featured', 'grid', 'rail']).default('featured'), imageFit: z.enum(['cover', 'contain']).default('cover'), showFilters: z.boolean().default(true),
  items: z.array(z.object({ title: z.string().default(''), category: z.string().default(''), description: z.string().default(''), imageUrl: z.string().default(''), imageAlt: z.string().default(''), href: safeLink, linkLabel: z.string().default('Explore project') })).max(60).default([]),
  cta: z.object({ label: z.string().default('View all work'), href: safeLink }).optional(),
})
function PortfolioFrame({ children, categories, filters, layout, scope }: { children: ReactNode; categories: string[]; filters: boolean; layout: string; scope?: string }) {
  return scope ? <PortfolioScope id={`awb-portfolio-${scope.replace(/[^a-zA-Z0-9_-]/g, '')}`} categories={categories} filters={filters} layout={layout}>{children}</PortfolioScope> : <PortfolioInteractive categories={categories} filters={filters} layout={layout}>{children}</PortfolioInteractive>
}
function PortfolioInteractive(props: Omit<Parameters<typeof PortfolioFrame>[0], 'scope'>) {
  const id = `awb-portfolio-${useId().replace(/[^a-zA-Z0-9_-]/g, '')}`
  return <PortfolioScope {...props} id={id} />
}
function PortfolioScope({ id, children, categories, filters, layout }: Omit<Parameters<typeof PortfolioFrame>[0], 'scope'> & { id: string }) {
  const variants = filters ? categories.map((_, index) => ({
    ancestor: `#${id}:has(input[data-filter="${index}"]:checked)`,
    childSelector: `[data-category="${index}"]`,
    count: Children.toArray(children).filter(child => isValidElement<{ 'data-category': number }>(child) && child.props['data-category'] === index).length,
  })) : []
  return <div id={id} style={{ containerType: 'inline-size', minWidth: 0 }}><style>{`#${id} .awb-project-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,330px),1fr));gap:2rem}#${id} .awb-project-grid.rail{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;padding:4px 0 20px;gap:1.5rem}#${id} .awb-project-grid.rail>article{flex:0 0 min(82vw,500px);scroll-snap-align:start}#${id} .awb-project-card{transition:transform .2s ease}#${id} .awb-project-card:focus-within{outline:2px solid var(--awb-primary);outline-offset:5px}#${id} label:has(input:checked){background:var(--awb-primary)!important;color:var(--awb-primary-fg)!important}#${id} label:focus-within{outline:2px solid var(--awb-primary);outline-offset:3px}${categories.map((_, index) => `#${id}:has(input[data-filter="${index}"]:checked) .awb-project-card:not([data-category="${index}"]){display:none}`).join('')}@media(prefers-reduced-motion:reduce){#${id} .awb-project-card{transition:none}}`}</style>{filters && categories.length > 1 && <div role="group" aria-label="Filter projects and products" style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: '2rem' }}>{['All', ...categories].map((label, index) => <label key={index} style={{ position: 'relative', cursor: 'pointer', padding: '0.65rem 1.1rem', border: '1px solid var(--awb-border)', borderRadius: '999px', fontSize: '0.85rem' }}><input type="radio" name={`${id}-filter`} data-filter={index - 1} defaultChecked={index === 0} style={{ position: 'absolute', opacity: 0, width: 1, height: 1 }} />{label}</label>)}</div>}<BalancedGrid variants={variants} count={Children.count(children)} minimumWidth={330} gap="2rem" enabled={layout !== 'rail'} className={`awb-project-grid ${layout}`}>{children}</BalancedGrid></div>
}
export const portfolioShowcase = defineComponent({
  componentId: 'PortfolioShowcase', version: '1.0.0', family: 'PORTFOLIO', name: 'Portfolio & product showcase',
  description: 'Large image-led projects or products with category filters, featured grid or swipeable image cards.',
  aiGuidance: 'Use only products or completed work supplied by the user. Never invent client names, outcomes, case studies or product photos. Use uploaded image URLs and factual descriptions; leave items empty if no real work is supplied. Use category labels, meaningful destination links and a relevant CTA.',
  propsSchema: portfolioProps,
  editorFields: [{ path: '/eyebrow', label: 'Eyebrow', type: 'text' }, { path: '/heading', label: 'Heading', type: 'text', headingLevel: 2 }, { path: '/intro', label: 'Introduction', type: 'textarea' }, { path: '/layout', label: 'Showcase layout', type: 'select', options: ['featured', 'grid', 'rail'] }, { path: '/imageFit', label: 'Image fit', type: 'select', options: ['cover', 'contain'] }, { path: '/showFilters', label: 'Show category filters', type: 'boolean' }, { path: '/items', label: 'Projects or products', type: 'list' }, { path: '/cta/label', label: 'View-all button label', type: 'text' }, { path: '/cta/href', label: 'View-all page link', type: 'link' }],
  tokenDeps: ['palette.primary', 'palette.background', 'palette.surface'], fixture: portfolioProps.parse({}),
  render: ({ props, context }) => {
    if (!props.items.length && !context.editing) return null
    const categories = [...new Set(props.items.map(item => item.category.trim()).filter(Boolean))]
    return <Section><Container><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'end', gap: '2rem', flexWrap: 'wrap', marginBottom: '2.5rem' }}><div style={{ maxWidth: '760px' }}>{props.eyebrow && <p data-awb-element="/eyebrow" style={{ color: 'var(--awb-primary)', textTransform: 'uppercase', letterSpacing: '0.16em', fontSize: '0.75rem', ...elementColor(props, '/eyebrow') }}>{props.eyebrow}</p>}<Heading level={2} data-awb-element="/heading" style={elementColor(props, '/heading')}>{props.heading}</Heading>{props.intro && <Prose data-awb-element="/intro" style={elementColor(props, '/intro')}>{props.intro}</Prose>}</div>{props.cta?.href && <Cta {...props.cta} data-awb-element="/cta" variant="outline" style={elementColor(props, '/cta')} />}</div>{!props.items.length && <p style={{ padding: '3rem', border: '1px dashed var(--awb-border)' }}>Add your first project or product in Properties. Upload its image, add a title, category and optional link.</p>}<PortfolioFrame categories={categories} filters={props.showFilters && !context.editing} layout={props.layout} scope={context.staticRenderScope}>{props.items.map((item, index) => <article key={index} className="awb-project-card" data-category={categories.indexOf(item.category.trim())} data-awb-element={`/items/${index}`} style={{ minWidth: 0, overflow: 'hidden', borderRadius: 'max(var(--awb-radius), 18px)', background: 'var(--awb-surface)', border: '1px solid var(--awb-border)', ...cardColor(props, `/items/${index}`) }}><div style={{ overflow: 'hidden', background: 'var(--awb-bg)' }}><Media src={item.imageUrl} alt={item.imageAlt || item.title} ratio="16 / 10" data-awb-element={`/items/${index}/imageUrl`} sizeStyle={imageSizing(props, `/items/${index}/imageUrl`)} style={{ objectFit: props.imageFit }} /></div><div style={{ padding: 'clamp(1.25rem,3vw,2.25rem)' }}>{item.category && <p data-awb-element={`/items/${index}/category`} style={{ fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.13em', margin: '0 0 0.85rem', ...elementColor(props, `/items/${index}/category`) }}>{item.category}</p>}<Heading level={3} data-awb-element={`/items/${index}/title`} style={elementColor(props, `/items/${index}/title`)}>{item.title}</Heading>{item.description && <Prose data-awb-element={`/items/${index}/description`} style={elementColor(props, `/items/${index}/description`)}>{item.description}</Prose>}{item.href && <Cta label={item.linkLabel || 'Explore'} href={item.href} variant="text-link" data-awb-element={`/items/${index}/linkLabel`} style={elementColor(props, `/items/${index}/linkLabel`)} />}</div></article>)}</PortfolioFrame></Container></Section>
  },
})
const credentialsProps = z.object({
  eyebrow: z.string().default('Recognition'), heading: z.string().default('Credentials & accolades'), intro: z.string().default(''),
  layout: z.enum(['grid', 'rail', 'compact']).default('grid'),
  items: z.array(z.object({ title: z.string().default(''), issuer: z.string().default(''), year: z.string().default(''), description: z.string().default(''), imageUrl: z.string().default(''), imageAlt: z.string().default(''), href: safeLink })).max(60).default([]),
})
export const credentialsShowcase = defineComponent({
  componentId: 'CredentialsShowcase', version: '1.0.0', family: 'CREDENTIALS', name: 'Credentials, awards & partner badges', description: 'A refined badge wall or horizontal rail for uploaded awards, certifications, accreditations and partner logos.',
  aiGuidance: 'Include only real awards, certifications, accreditations or partnerships explicitly supplied by the user. Never generate badge artwork, logos, issuers, years or claims. Leave items empty when none are supplied. Use the user-uploaded badge image and optional verification link.',
  propsSchema: credentialsProps,
  editorFields: [{ path: '/eyebrow', label: 'Eyebrow', type: 'text' }, { path: '/heading', label: 'Heading', type: 'text', headingLevel: 2 }, { path: '/intro', label: 'Introduction', type: 'textarea' }, { path: '/layout', label: 'Badge layout', type: 'select', options: ['grid', 'rail', 'compact'] }, { path: '/items', label: 'Credentials and badges', type: 'list' }], tokenDeps: ['palette.surface', 'palette.primary'], fixture: credentialsProps.parse({}),
  render: ({ props, context }) => {
    if (!props.items.length && !context.editing) return null
    return <Section background="surface"><Container><div style={{ maxWidth: 780, margin: '0 auto 3rem', textAlign: 'center' }}>{props.eyebrow && <p data-awb-element="/eyebrow" style={{ textTransform: 'uppercase', letterSpacing: '0.18em', fontSize: '0.75rem', color: 'var(--awb-primary)', ...elementColor(props, '/eyebrow') }}>{props.eyebrow}</p>}<Heading level={2} data-awb-element="/heading" style={elementColor(props, '/heading')}>{props.heading}</Heading>{props.intro && <Prose data-awb-element="/intro" style={{ marginInline: 'auto', ...elementColor(props, '/intro') }}>{props.intro}</Prose>}</div>{!props.items.length && <p style={{ border: '1px dashed var(--awb-border)', padding: '3rem', textAlign: 'center' }}>Upload your real awards, credentials or partner badges in Properties. Nothing is claimed or displayed publicly until you add an item.</p>}<BalancedGrid count={props.items.length} minimumWidth={props.layout === 'compact' ? 145 : 210} gap="1.25rem" enabled={props.layout !== 'rail'} style={{ display: props.layout === 'rail' ? 'flex' : 'grid', gridTemplateColumns: `repeat(auto-fit,minmax(min(100%,${props.layout === 'compact' ? 145 : 210}px),1fr))`, gap: '1.25rem', overflowX: props.layout === 'rail' ? 'auto' : undefined, scrollSnapType: 'x mandatory', paddingBottom: props.layout === 'rail' ? '1rem' : undefined }}>{props.items.map((item, index) => <article key={index} data-awb-element={`/items/${index}`} style={{ flex: props.layout === 'rail' ? '0 0 240px' : undefined, scrollSnapAlign: 'start', padding: props.layout === 'compact' ? '1.25rem' : '2rem', textAlign: 'center', background: 'var(--awb-bg)', border: '1px solid var(--awb-border)', borderRadius: 'max(var(--awb-radius), 16px)', ...cardColor(props, `/items/${index}`) }}><Media src={item.imageUrl} alt={item.imageAlt || item.title} ratio="4 / 3" data-awb-element={`/items/${index}/imageUrl`} sizeStyle={imageSizing(props, `/items/${index}/imageUrl`)} style={{ objectFit: 'contain', maxHeight: props.layout === 'compact' ? 110 : 170, marginBottom: '1.25rem' }} /><Heading level={3} data-awb-element={`/items/${index}/title`} style={{ fontSize: '1.1rem', ...elementColor(props, `/items/${index}/title`) }}>{item.title}</Heading><p style={{ fontSize: '0.8rem', color: 'var(--awb-muted)' }}><span data-awb-element={`/items/${index}/issuer`} style={elementColor(props, `/items/${index}/issuer`)}>{item.issuer}</span>{item.issuer && item.year && ' · '}<span data-awb-element={`/items/${index}/year`} style={elementColor(props, `/items/${index}/year`)}>{item.year}</span></p>{item.description && <Prose data-awb-element={`/items/${index}/description`} style={{ fontSize: '0.85rem', ...elementColor(props, `/items/${index}/description`) }}>{item.description}</Prose>}{item.href && <a data-awb-element={`/items/${index}/href`} style={{ fontSize: '0.8rem', color: 'var(--awb-primary)', ...elementColor(props, `/items/${index}/href`) }} href={item.href}>View credential ↗</a>}</article>)}</BalancedGrid></Container></Section>
  },
})
