import Link from 'next/link'
import { prisma } from '@awb/database'
import { requireAdmin } from '@/lib/tenancy'
import { AppShell } from '@/components/account/app-shell'
import { ActionForm } from '@/components/account/action-form'
import { EmailFields, AudienceField } from '@/components/account/email-fields'
import { saveEmailSettings, saveEmailStep, saveEmailCampaign } from '@/app/actions/marketing'
export default async function EmailAdminPage() {
  await requireAdmin()
  const [settings, steps, campaigns, subscribed, sent, failures] = await Promise.all([
    prisma.emailMarketingSettings.findUniqueOrThrow({ where: { id: 'main' } }),
    prisma.emailSequenceStep.findMany({ orderBy: [{ delayDays: 'asc' }, { name: 'asc' }] }),
    prisma.emailCampaign.findMany({ orderBy: { createdAt: 'desc' }, take: 30, include: { _count: { select: { deliveries: true } } } }),
    prisma.emailContact.count({ where: { optedIn: true } }), prisma.emailDelivery.count({ where: { status: 'SENT' } }),
    prisma.emailDelivery.findMany({ where: { status: { in: ['FAILED', 'UNKNOWN'] } }, orderBy: { createdAt: 'desc' }, take: 15, include: { contact: { include: { user: { select: { email: true } } } } } }),
  ])
  return <AppShell title="Email studio" active="/admin/emails"><div className="wt-heading"><p className="wt-eyebrow">PLATFORM ADMIN</p><h1>A helpful next step, by email.</h1><p>Edit your onboarding sequence and send campaigns to the right customers.</p></div><div className="wt-stats"><div className="wt-card"><span>Subscribed users</span><strong>{subscribed}</strong></div><div className="wt-card"><span>Emails accepted by SES</span><strong>{sent}</strong></div><div className="wt-card"><span>Delivery</span><strong>{settings.deliveryEnabled ? 'Enabled' : 'Paused'}</strong></div></div><nav className="wt-email-tabs"><a href="#sequence">Onboarding sequence</a><a href="#campaigns">Email campaigns</a><a href="#email-settings">Settings</a></nav>
  <section id="sequence"><div className="wt-section-title"><h2>First login → paid plan</h2><span className="wt-badge">{settings.automationEnabled ? 'Sequence enabled' : 'Sequence paused'}</span></div><p className="wt-muted">Timing starts at the first successful login and never resets on later logins. The current website status chooses the message. Payment permanently stops this sequence. After day 7, weekly reminders continue until payment or unsubscribe. At most one automatic email per user every 24 hours; missed steps are not sent all at once.</p><div className="wt-email-steps">{steps.map(step => <details key={step.id} className="wt-card"><summary><strong>Day {step.delayDays} · {step.name}</strong><span>{step.enabled ? step.repeatDays ? `Every ${step.repeatDays} days after that` : 'Once' : 'Disabled'} · {step.websiteCondition === 'HAS_WEBSITE' ? 'Website created' : step.websiteCondition === 'NO_WEBSITE' ? 'No website yet' : 'Either website status'}</span></summary><ActionForm action={saveEmailStep} label="Save step"><input type="hidden" name="id" value={step.id} /><div className="wt-two-col"><label>Days after first login<input name="delayDays" type="number" min={0} max={365} defaultValue={step.delayDays} required /></label><label>Repeat every X days (0 = once)<input name="repeatDays" type="number" min={0} max={365} defaultValue={step.repeatDays} required /></label></div><EmailFields value={step} /><label className="wt-check"><input name="enabled" type="checkbox" defaultChecked={step.enabled} /> Enable this step</label></ActionForm></details>)}</div><details className="wt-card mt-4"><summary><strong>+ Add sequence step</strong></summary><ActionForm action={saveEmailStep} label="Add step"><EmailFields /><label>Days after first login<input type="number" name="delayDays" defaultValue={10} min={0} max={365} required /></label><label>Repeat every X days (0 = once)<input type="number" name="repeatDays" defaultValue={0} min={0} max={365} required /></label><label className="wt-check"><input name="enabled" type="checkbox" defaultChecked /> Enable this step</label></ActionForm></details></section>
  <section id="campaigns" className="mt-8"><h2>Email campaigns</h2><p className="wt-muted">Recipients are subscribed, active workspace owners. Paid and unpaid groups exclude complimentary accounts. Each person receives a campaign once, even if they own several workspaces. Account status is checked again at delivery.</p><details className="wt-card"><summary><strong>+ Create email campaign</strong></summary><ActionForm action={saveEmailCampaign} label="Save draft & preview"><AudienceField /><EmailFields /></ActionForm></details><div className="wt-table-wrap mt-4"><table className="wt-table"><thead><tr><th>Campaign</th><th>Audience</th><th>Status</th><th>Recipients queued</th></tr></thead><tbody>{campaigns.map(c => <tr key={c.id}><td><Link href={`/admin/emails/campaigns/${c.id}`}>{c.name} →</Link></td><td>{c.audience.toLowerCase()}</td><td>{c.status.toLowerCase()}</td><td>{c._count.deliveries}</td></tr>)}</tbody></table>{!campaigns.length && <p className="p-4 wt-muted">No campaigns yet. Create a draft to review your message and audience.</p>}</div></section>
  <section id="email-settings" className="wt-card mt-8"><h2>Email settings</h2><ActionForm action={saveEmailSettings} label="Save email settings"><label>Sender display name<input name="senderName" defaultValue={settings.senderName} required maxLength={80} /></label><p className="wt-muted">Sending address: {process.env.SES_MAILER_FROM ? 'Configured with Amazon SES' : 'Not configured'}</p><label>Business mailing address<textarea name="mailingAddress" defaultValue={settings.mailingAddress} rows={3} maxLength={500} placeholder="Your business mailing address, included in every promotional email" /></label><label>Maximum promotional emails per day (UTC)<input name="dailyLimit" type="number" min={1} max={100000} defaultValue={settings.dailyLimit} required /></label><label className="wt-check"><input name="deliveryEnabled" type="checkbox" defaultChecked={settings.deliveryEnabled} /> Enable background promotional email delivery</label><label className="wt-check"><input name="automationEnabled" type="checkbox" defaultChecked={settings.automationEnabled} /> Run the first-login sequence for subscribed users</label><p className="wt-muted">Turning delivery off pauses both campaigns and sequences. Verification, password reset and content-ready emails are separate. SES must be ready for your intended recipients.</p></ActionForm></section>
  {!!failures.length && <section className="wt-card mt-8"><h2>Delivery needs attention</h2>{failures.map(f => <div className="wt-audit" key={f.id}><strong>{f.contact.user.email}</strong><span>{f.status}</span><small>{f.detail}</small></div>)}</section>}</AppShell>
}
