import { renderEmailDesign } from '@awb/shared/email-render'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { prisma } from '@awb/database'
import { countAudience, renderMarketing, contactInclude, matchesAudience } from '@awb/database/marketing'
import { requireAdmin } from '@/lib/tenancy'
import { appUrl } from '@/lib/account-security'
import { AppShell } from '@/components/account/app-shell'
import { ActionForm } from '@/components/account/action-form'
import { EmailFields, AudienceField } from '@/components/account/email-fields'
import { saveEmailCampaign, queueEmailCampaign, cancelEmailCampaign } from '@/app/actions/marketing'
export default async function EmailCampaignPage({ params }: { params: Promise<{ id: string }> }) {
  await requireAdmin(); const { id } = await params
  const campaign = await prisma.emailCampaign.findUnique({ where: { id } }); if (!campaign) notFound()
  const [count, settings, stats, contacts] = await Promise.all([countAudience(campaign.audience, campaign.websiteCondition), prisma.emailMarketingSettings.findUniqueOrThrow({ where: { id: 'main' } }), prisma.emailDelivery.groupBy({ by: ['status'], where: { campaignId: id }, _count: true }), prisma.emailContact.findMany({ where: { optedIn: true }, include: contactInclude, take: 100 })])
  const sample = contacts.find(c => matchesAudience(c, campaign.audience, campaign.websiteCondition))
  const preview = sample ? renderMarketing(campaign.subject, campaign.body, sample, appUrl(), settings.mailingAddress || '[Business mailing address]') : null
  const body = preview ? preview.body.replaceAll(preview.unsubscribe, `${appUrl()}/email-preferences?token=[recipient-specific]`) : `${campaign.body}\n\nWebtummy\n${settings.mailingAddress || '[Business mailing address]'}\n\nUnsubscribe: [recipient-specific link]`
  const designPreview = campaign.bodyDesign ? renderEmailDesign(campaign.bodyDesign, preview?.values ?? { name: 'Alex', website_name: 'Your website', dashboard_url: `${appUrl()}/dashboard`, billing_url: `${appUrl()}/billing`, trial_end: 'your trial end date', unsubscribe_url: `${appUrl()}/email-preferences` }, appUrl(), settings.mailingAddress || '[Business mailing address]', `${appUrl()}/email-preferences`) : null
  return <AppShell title="Campaign preview" active="/admin/emails"><Link href="/admin/emails">← Email studio</Link><div className="wt-heading"><h1>{campaign.name}</h1><p>{campaign.status.toLowerCase()} · {count} currently eligible subscribers · {campaign.audience.toLowerCase()}</p></div><div className="wt-two-col"><section className="wt-card"><h2>Message preview</h2><p className="wt-muted">{sample ? 'Personalised sample from the selected audience.' : 'Placeholders will be personalised for each eligible recipient.'}</p><h3>{preview?.subject ?? campaign.subject}</h3><>{designPreview && <iframe title="Campaign HTML preview" srcDoc={designPreview} sandbox="" style={{ width: '100%', height: 650, border: 0 }} />}<details open={!designPreview}><summary>Plain-text version</summary><pre className="wt-email-preview">{body}</pre></details></></section><section className="wt-card"><h2>{campaign.status === 'DRAFT' ? 'Review and queue' : 'Delivery progress'}</h2>{campaign.status === 'DRAFT' ? <><p>The worker sends individually through SES. Users who unsubscribe or leave this audience before delivery are skipped. New subscribers after queuing are not added.</p><ActionForm action={queueEmailCampaign} label="Queue campaign" disabled={count === 0 || !settings.deliveryEnabled}><input type="hidden" name="id" value={id} /><input type="hidden" name="version" value={campaign.updatedAt.toISOString()} /><label className="wt-check"><input name="confirm" type="checkbox" required /> I reviewed this message and the selected audience.</label></ActionForm>{!settings.deliveryEnabled && <p className="wt-message">Delivery is paused. Enable it in Email settings.</p>}{count === 0 && <p className="wt-muted">There are no eligible subscribers in this audience yet.</p>}</> : <><ul>{stats.map(s => <li key={s.status}>{s.status.toLowerCase()}: {s._count}</li>)}</ul><p className="wt-muted">“Sent” means SES accepted the message, not that it reached the inbox. Refresh this page to update counts.</p><Link className="wt-button secondary" href={`/admin/emails/campaigns/${id}`}>Refresh progress</Link></>}{['DRAFT', 'QUEUED'].includes(campaign.status) && <div className="mt-6"><ActionForm action={cancelEmailCampaign} label="Cancel campaign"><input type="hidden" name="id" value={id} /></ActionForm></div>}</section></div>{campaign.status === 'DRAFT' && <details className="wt-card mt-6"><summary><strong>Edit draft</strong></summary><ActionForm action={saveEmailCampaign} label="Save & refresh preview"><input type="hidden" name="id" value={id} /><AudienceField value={campaign.audience} /><EmailFields value={campaign} /></ActionForm></details>}</AppShell>
}
