import { saveMarketingPreference } from '@/app/actions/marketing'
import { SocialButtons } from '@/components/account/social-buttons'
import Link from 'next/link'
import { prisma } from '@awb/database'
import { requirePageUser } from '@/lib/tenancy'
import { updateProfile, requestPasswordReset } from '@/app/actions/account'
import { AppShell } from '@/components/account/app-shell'
import { ActionForm } from '@/components/account/action-form'
export default async function AccountPage() {
  const user = await requirePageUser(); const profile = await prisma.user.findUniqueOrThrow({ where: { id: user.id }, include: { emailContact: true } })
  return <AppShell title="Account settings" active="/account"><div className="wt-heading"><p className="wt-eyebrow">YOUR ACCOUNT</p><h1>A little about you.</h1><p>Manage your profile and keep your account secure.</p></div><div className="wt-two-col"><section className="wt-card"><h2>Profile</h2><ActionForm action={updateProfile} label="Save profile"><label>Name<input name="name" defaultValue={user.name ?? ''} required minLength={2} maxLength={100} /></label><label>Email<input value={user.email} readOnly /></label><p className="wt-muted">{profile.emailVerified ? 'Email verified' : 'Verify your email by setting a password below.'}</p></ActionForm></section><section className="wt-card"><h2>Security</h2><p className="wt-muted">{profile.passwordHash ? 'Change your password using a secure email link.' : 'Set a password for future sign-ins. Your current session remains available until the password is set.'}</p><ActionForm action={requestPasswordReset} label={profile.passwordHash ? 'Email password reset link' : 'Email password setup link'}><input type="hidden" name="email" value={user.email} /></ActionForm><div className="wt-divider" /><h3>Connected sign-in</h3><p className="wt-muted">Connect your own Google or Microsoft account while signed in. Existing accounts are never automatically merged by email.</p><SocialButtons connecting />{user.isPlatformAdmin && <p className="wt-success">Platform administrator · <Link href="/admin">Open Admin →</Link></p>}</section></div><section className="wt-card mt-6"><h2>Email preferences</h2><ActionForm action={saveMarketingPreference} label="Save email preferences"><label className="wt-check"><input type="checkbox" name="optedIn" defaultChecked={profile.emailContact?.optedIn ?? false} /> Send me website tips and Webtummy offers.</label><p className="wt-muted">Optional. You can unsubscribe at any time. Account, security and content-ready emails are separate.</p></ActionForm></section></AppShell>
}
