'use client'
import { ErrorNotice } from '@/components/error-notice'
/* Social icons share fixed public PNG URLs with the email renderer. */
/* eslint-disable @next/next/no-img-element */
import type { EmailBlock } from '@awb/shared/email-design'
import { emailSocialPlatforms, emailSocialNames, emailSocialIconUrl, emailSocialUrl } from '@awb/shared/email-social'
export function EmailSocialProperties({ block, update }: { block: EmailBlock; update: (patch: Partial<EmailBlock>) => void }) {
  const missing = emailSocialPlatforms.filter(platform => !block.socialLinks.some(link => link.platform === platform))
  const patch = (platform: typeof emailSocialPlatforms[number], change: Partial<EmailBlock['socialLinks'][number]>) => update({ socialLinks: block.socialLinks.map(link => link.platform === platform ? { ...link, ...change } : link) })
  return <div className="wt-email-social-properties"><h3>Social profiles</h3><p className="wt-muted">All icons appear here for editing. Only icons with a link appear in preview and sent emails.</p><label>Icon size<input type="range" min={16} max={64} value={block.iconSize} onChange={e => update({ iconSize: Number(e.target.value) })} /><small>{block.iconSize}px</small></label><label>Space between icons<input type="range" min={0} max={32} value={block.iconGap} onChange={e => update({ iconGap: Number(e.target.value) })} /><small>{block.iconGap}px</small></label>{block.socialLinks.map(link => <div className="wt-email-social-profile" key={link.platform}><div className="wt-email-social-profile-title"><img src={emailSocialIconUrl(link.platform, link.color ?? block.color)} width={20} height={20} alt="" /><strong>{emailSocialNames[link.platform]}</strong><button type="button" aria-label={`Remove ${emailSocialNames[link.platform]} icon`} title={`Remove ${emailSocialNames[link.platform]}`} onClick={() => update({ socialLinks: block.socialLinks.filter(item => item.platform !== link.platform) })}>×</button></div><label>{emailSocialNames[link.platform]} link<input type="text" value={link.href} placeholder="https://…" maxLength={2000} aria-invalid={!emailSocialUrl(link.href)} onChange={e => patch(link.platform, { href: e.target.value })} /></label>{!emailSocialUrl(link.href) && <ErrorNotice code="WT-FORM-001" message="Enter a full http:// or https:// address." />}<label>{emailSocialNames[link.platform]} colour<input type="color" value={link.color ?? block.color} onChange={e => patch(link.platform, { color: e.target.value })} /></label>{link.color && <button type="button" onClick={() => patch(link.platform, { color: null })}>Use row colour</button>}</div>)}{missing.length > 0 && <><label>Add an icon<select value="" onChange={e => { const platform = missing.find(item => item === e.target.value); if (platform) update({ socialLinks: [...block.socialLinks, { platform, href: '', color: null }] }) }}><option value="">Choose social platform</option>{missing.map(platform => <option key={platform} value={platform}>{emailSocialNames[platform]}</option>)}</select></label><button type="button" onClick={() => update({ socialLinks: [...block.socialLinks, ...missing.map(platform => ({ platform, href: '', color: null }))] })}>Add all missing icons</button></>}</div>
}
