import assert from 'node:assert/strict'
import { emailBlockSchema, designFromText, emailUrl } from '@awb/shared/email-design'
import { cleanEmailDesign, emailDesignText, renderEmailDesign } from '@awb/shared/email-render'
const base = 'https://app.example.invalid'
const design = designFromText('Hi {{name}},\n\nYour website is ready.')
design.blocks.push(emailBlockSchema.parse({ id: 'image', type: 'image', src: '/api/email-images/12345678-1234-1234-1234-123456789abc.png', alt: 'Our image', width: 80 }))
design.blocks.push(emailBlockSchema.parse({ id: 'cta', type: 'button', href: '{{billing_url}}', label: 'Choose a plan', fill: '#123456', color: '#ffffff' }))
design.blocks[0]!.html += '<p><a href="{{dashboard_url}}">Open dashboard</a><strong>Bold</strong><em>Italic</em><span style="color:#123456;font-size:24px">Styled</span></p><script>alert(1)</script><img src=x onerror=alert(1)><a href="javascript:alert(1)">Bad link</a><span style="position:fixed;background-image:url(https://evil.invalid)">Unsafe CSS</span>'
const cleaned = cleanEmailDesign(design)
assert.ok(!cleaned.blocks[0]!.html.includes('<script'))
assert.ok(!cleaned.blocks[0]!.html.includes('javascript:'))
assert.ok(!cleaned.blocks[0]!.html.includes('onerror'))
assert.ok(!cleaned.blocks[0]!.html.includes('position:'))
assert.ok(cleaned.blocks[0]!.html.includes('color:#123456'))
assert.ok(cleaned.blocks[0]!.html.includes('{{dashboard_url}}'))
const html = renderEmailDesign(cleaned, { name: '<img src=x onerror=alert(1)>', dashboard_url: base + '/dashboard', billing_url: base + '/billing' }, base, 'Business & Address', base + '/email-preferences?token=test')
assert.ok(html.includes(`href="${base}/billing"`))
assert.ok(html.includes(`href="${base}/dashboard"`))
assert.ok(html.includes(`src="${base}/api/email-images/`))
assert.ok(html.includes('background-color:#123456;color:#ffffff'))
assert.ok(html.includes('Unsubscribe from onboarding'))
assert.ok(html.includes('Business &amp; Address'))
assert.ok(!html.includes('<img src=x'))
assert.ok(html.includes('&lt;img'))
assert.ok(emailDesignText(cleaned).includes('Choose a plan: {{billing_url}}'))
assert.equal(emailUrl('javascript:alert(1)'), false)
assert.equal(emailUrl('https://example.com/logo.png', true), true)
assert.equal(emailUrl('data:image/svg+xml,bad', true), false)
assert.throws(() => cleanEmailDesign({ ...design, blocks: [...design.blocks, design.blocks[0]] }), /unique/)
console.log('PASS: HTML email rendering, safe rich text, colours, links, images, token escaping, unsubscribe footer, plain-text fallback and schema validation.')

const { emailSocialPlatforms, emailSocialIconUrl, emailSocialSvg } = await import('@awb/shared/email-social')
const socials = emailBlockSchema.parse({ id: 'socials', type: 'social', color: '#445566', socialLinks: emailSocialPlatforms.map(platform => ({ platform, href: platform === 'facebook' ? 'https://facebook.com/webtummy?a=1&b=2' : platform === 'linkedin' ? 'https://linkedin.com/company/webtummy' : '', color: platform === 'facebook' ? '#123456' : null })) })
const socialDesign = { ...designFromText('Follow us for updates.'), blocks: [socials] }
const socialHtml = renderEmailDesign(socialDesign, {}, base, 'Mailing address', base + '/unsubscribe')
assert.ok(socialHtml.includes('https://facebook.com/webtummy?a=1&amp;b=2'))
assert.ok(socialHtml.includes('/api/email-social-icons/facebook/123456.png'))
assert.ok(socialHtml.includes('/api/email-social-icons/linkedin/445566.png'))
assert.ok(!socialHtml.includes('instagram'), 'Empty profiles do not appear in sent email')
assert.ok(!socialHtml.includes('<svg'), 'Outgoing icons use email-compatible PNGs')
assert.ok(emailDesignText(socialDesign).includes('LinkedIn: https://linkedin.com/company/webtummy'))
assert.ok(!emailDesignText(socialDesign).includes('Instagram'))
assert.throws(() => cleanEmailDesign({ ...socialDesign, blocks: [{ ...socials, socialLinks: [{ platform: 'facebook', href: 'javascript:alert(1)' }] }] }), /HTTP/)
assert.throws(() => cleanEmailDesign({ ...socialDesign, blocks: [{ ...socials, socialLinks: [socials.socialLinks[0], socials.socialLinks[0]] }] }), /repeat/)
assert.throws(() => emailSocialIconUrl('facebook', '#bad<script>'))
assert.ok(emailSocialSvg('instagram', '#aabbcc').includes('stroke="#aabbcc"'))
assert.deepEqual(emailBlockSchema.parse({ id: 'old', type: 'text' }).socialLinks, [], 'Old email designs remain compatible')
console.log('PASS: social icon links, row/per-icon colours, PNG email output, blank-profile omission, plain-text links, URL validation and existing-design compatibility.')

const htmlDesign = { ...designFromText('Visual blocks stay here.'), mode: 'html' as const, sourceHtml: `<!doctype html><html><head><style>.headline { color:#123456; font-size:28px; } @media screen and (max-width:600px) { .wrapper { width:100% !important; } } @import url(https://evil.invalid/css); .bad { position:fixed; background-image:url(https://evil.invalid/tracker); }</style></head><body style="background-color:#eeeeee"><table class="wrapper" width="600" cellpadding="0"><tr><td><h1 class="headline">Hello {{name}}</h1><p>Try this &amp; that.</p><a href="{{billing_url}}">Choose your plan</a><img src="https://images.example.invalid/logo.png" alt="Logo" width="100" onerror="alert(1)"><script>alert(1)</script><iframe src="https://evil.invalid"></iframe><form action="https://evil.invalid"><input name="password"></form><a href="javascript:alert(1)">Bad</a></td></tr></table></body></html>` }
const safeHtmlDesign = cleanEmailDesign(htmlDesign)
assert.equal(safeHtmlDesign.mode, 'html')
assert.ok(safeHtmlDesign.sourceHtml.includes('color:#123456') || safeHtmlDesign.sourceHtml.includes('color: #123456'), 'Embedded CSS is inlined')
assert.ok(safeHtmlDesign.sourceHtml.includes('@media'), 'Responsive media rules are retained')
assert.ok(!safeHtmlDesign.sourceHtml.includes('evil.invalid'))
assert.ok(!safeHtmlDesign.sourceHtml.includes('<script'))
assert.ok(!safeHtmlDesign.sourceHtml.includes('<iframe'))
assert.ok(!safeHtmlDesign.sourceHtml.includes('<form'))
assert.ok(!safeHtmlDesign.sourceHtml.includes('onerror'))
assert.ok(!safeHtmlDesign.sourceHtml.includes('javascript:'))
const full = renderEmailDesign(htmlDesign, { name: '<img src=x onerror=alert(1)>', billing_url: base + '/billing' }, base, 'Business address', base + '/unsubscribe')
assert.equal((full.match(/Unsubscribe from onboarding/g) || []).length, 1)
assert.ok(full.includes(`href="${base}/billing"`))
assert.ok(full.includes('&lt;img'))
assert.ok(!full.includes('<img src=x'))
assert.ok(full.includes('src="https://images.example.invalid/logo.png"'))
assert.ok(emailDesignText(htmlDesign).includes('Try this & that.'))
assert.ok(emailDesignText(htmlDesign).includes('Choose your plan ({{billing_url}})'))
assert.ok(!emailDesignText(htmlDesign).includes('@media'))
const visualSource = renderEmailDesign(designFromText('Hello {{name}}'), { name: '{{name}}' }, base, 'Address', base + '/unsubscribe', false)
assert.ok(visualSource.includes('{{name}}'))
assert.ok(!visualSource.includes('Unsubscribe from onboarding'))
assert.throws(() => cleanEmailDesign({ ...htmlDesign, sourceHtml: '<script>alert(1)</script>' }), /visible/)
assert.throws(() => cleanEmailDesign({ ...htmlDesign, sourceHtml: '' }), /template/)
assert.equal(cleanEmailDesign({ ...htmlDesign, mode: 'visual' }).blocks[0]!.html, htmlDesign.blocks[0]!.html, 'HTML mode never replaces visual blocks')
console.log('PASS: full HTML mode, CSS inlining, responsive rules, HTML safety, escaped personalisation, image preservation, text fallback, single required footer and visual-source export.')
