import 'dotenv/config'
import assert from 'node:assert/strict'
import { randomBytes } from 'node:crypto'
import { createRequire } from 'node:module'
import { prisma } from '@awb/database'
import { hashPassword } from '../apps/web/src/lib/account-security'
const {chromium}=createRequire(import.meta.url)('/tmp/webtummy-preview/node_modules/playwright')
const base=process.env.MARKETING_TEST_BASE||'http://127.0.0.1:3002'
const tag=randomBytes(6).toString('hex'),password=randomBytes(18).toString('hex')
const users:string[]=[],workspaces:string[]=[]
let browser:any
async function signIn(email:string){const page=await browser.newPage();await page.goto(base+'/signin');await page.locator('#signin-email').fill(email);await page.locator('#signin-password').fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(/\/dashboard/);return page}
try{
 const passwordHash=await hashPassword(password)
 async function fixture(role:string,customer?:string){const user=await prisma.user.create({data:{email:`billing-${role}-${tag}@example.invalid`,name:`Billing ${role} check`,passwordHash,emailVerified:new Date(),isPlatformAdmin:role==='admin',isPlatformSupport:role==='support'}});users.push(user.id);const w=await prisma.workspace.create({data:{name:`Billing ${role} QA`,slug:`billing-${role}-${tag}`,stripeCustomerId:customer,billingStatus:'none',members:{create:{userId:user.id,role:'OWNER'}}}});workspaces.push(w.id);return {user,w}}
 const owner=await fixture('owner','cus_mockBillingA'),other=await fixture('other','cus_mockBillingB'),admin=await fixture('admin'),support=await fixture('support')
 browser=await chromium.launch({headless:true,executablePath:'/home/ubuntu/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox']})
 const anonymous=await browser.newPage();let response=await anonymous.request.get(`${base}/api/billing/invoices/in_mockBillingA1?workspaceId=${owner.w.id}`,{maxRedirects:0});assert.equal(response.status(),401);assert.equal((await response.json()).code,'WT-BILLING-002');await anonymous.close()
 const customer=await signIn(owner.user.email);await customer.goto(base+'/billing');await customer.getByRole('heading',{name:'Payment history',exact:true}).waitFor();assert.equal(await customer.getByRole('link',{name:'Download invoice PDF ↓'}).count(),2);assert.ok((await customer.locator('table').innerText()).includes('$29.00'));await customer.getByRole('link',{name:'Older payments →'}).click();await customer.waitForURL(/after=in_mockBillingA2/);await customer.getByText('WT-2026-3',{exact:true}).waitFor();assert.equal(await customer.getByRole('link',{name:'Download invoice PDF ↓'}).count(),1);await customer.getByRole('link',{name:'Latest payments →'}).click();await customer.waitForURL(base+'/billing');
 response=await customer.request.get(`${base}/api/billing/invoices/in_mockBillingA1?workspaceId=${owner.w.id}`,{maxRedirects:0});assert.equal(response.status(),302);assert.ok(response.headers()['location'].startsWith('https://pay.stripe.com/'));assert.equal(response.headers()['cache-control'],'private, no-store');
 response=await customer.request.get(`${base}/api/billing/invoices/in_mockBillingForeign?workspaceId=${owner.w.id}`,{maxRedirects:0});assert.equal(response.status(),403)
 response=await customer.request.get(`${base}/api/billing/invoices/in_mockBillingA1?workspaceId=${other.w.id}`,{maxRedirects:0});assert.equal(response.status(),403)
 response=await customer.request.get(`${base}/admin/billing/${owner.w.id}`);assert.equal(response.status(),404);await customer.goto(base+'/billing?after=in_mockBillingForeign');await customer.locator('[data-error-code="WT-BILLING-002"]').waitFor();assert.equal(await customer.getByRole('link',{name:'Download invoice PDF ↓'}).count(),0)
 const staff=await signIn(support.user.email);response=await staff.request.get(`${base}/admin/billing/${owner.w.id}`);assert.equal(response.status(),404);response=await staff.request.get(`${base}/api/billing/invoices/in_mockBillingA1?workspaceId=${owner.w.id}`,{maxRedirects:0});assert.equal(response.status(),403)
 const manager=await signIn(admin.user.email);await manager.goto(base+'/admin/users?q='+encodeURIComponent(owner.user.email));assert.equal(await manager.getByRole('link',{name:'View payments & subscription →'}).count(),1);await manager.getByRole('link',{name:'View payments & subscription →'}).click();await manager.waitForURL(base+'/admin/billing/'+owner.w.id);await manager.getByRole('heading',{name:'Payment history',exact:true}).waitFor();assert.equal(await manager.getByRole('link',{name:'Download invoice PDF ↓'}).count(),2);response=await manager.request.get(`${base}/api/billing/invoices/in_mockBillingA1?workspaceId=${owner.w.id}`,{maxRedirects:0});assert.equal(response.status(),302)
 await prisma.workspace.update({where:{id:owner.w.id},data:{stripeSubscriptionId:'sub_mockBillingA',billingStatus:'active',billingPaidThrough:new Date(Date.now()+25*86400000),billingLastReconciledAt:new Date()}})
 let submitted: { headers: Record<string, string>; body: string } | undefined
 manager.on('request', (request: any) => { if (request.method() === 'POST' && request.headers()['next-action']) submitted = { headers: request.headers(), body: request.postData() } })
 await manager.reload();await manager.locator('input[name=reason]').fill('Customer requested cancellation');await manager.locator('input[name=confirmed]').check();await manager.getByRole('button',{name:'Cancel subscription renewal',exact:true}).click();await manager.getByText('Renewal is cancelled. The subscription ends after the current paid period.',{exact:true}).waitFor();const updated=await prisma.workspace.findUniqueOrThrow({where:{id:owner.w.id}});assert.equal(updated.cancelAtPeriodEnd,true);assert.equal(updated.billingStatus,'active');assert.ok(updated.billingPaidThrough!>new Date());assert.equal(await prisma.auditEvent.count({where:{workspaceId:owner.w.id,actorId:admin.user.id,action:'admin.subscription.cancel-renewal'}}),1)
 assert.ok(submitted);for (const outsider of [customer, staff]) { await outsider.request.post(`${base}/admin/billing/${owner.w.id}`, { headers: { 'content-type': submitted!.headers['content-type'], 'next-action': submitted!.headers['next-action'], origin: base }, data: submitted!.body }); }
 assert.equal(await prisma.auditEvent.count({where:{workspaceId:owner.w.id,action:'admin.subscription.cancel-renewal'}}),1)
 console.log('PASS: real password login redirects; invoice pagination/download; anonymous, other-customer and support isolation; admin history and audited period-end cancellation. Stripe transport mocked; no live payment changes.')
}finally{if(browser)await browser.close();for(const id of workspaces)await prisma.workspace.deleteMany({where:{id}});await prisma.user.deleteMany({where:{id:{in:users}}});await prisma.$disconnect()}
