import Link from 'next/link'
import { prisma } from '@awb/database'
import { requireAdmin } from '@/lib/tenancy'
import { AppShell } from '@/components/account/app-shell'
import { ActionForm } from '@/components/account/action-form'
import { manageWorkspace } from '@/app/actions/admin'
export default async function AdminPage({ searchParams }: { searchParams: Promise<{ page?: string }> }) {
  await requireAdmin(); const query = await searchParams; const page = Math.max(1, Math.min(10000, Number(query.page) || 1))
  const [users, websites, subscribers, total, workspaces, audit] = await Promise.all([prisma.user.count(), prisma.project.count(), prisma.workspace.count({ where: { billingStatus: 'active', billingExempt: false } }), prisma.workspace.count(), prisma.workspace.findMany({ orderBy: { createdAt: 'desc' }, skip: (page - 1) * 20, take: 20, include: { billingPlan: true, _count: { select: { projects: true, members: true } } } }), prisma.auditEvent.findMany({ where: { OR: [{ action: { startsWith: 'admin.' } }, { action: { startsWith: 'billing.' } }] }, orderBy: { createdAt: 'desc' }, take: 10, include: { actor: { select: { email: true } } } })])
  return <AppShell title="Platform overview" active="/admin"><div className="wt-heading"><p className="wt-eyebrow">PLATFORM ADMIN</p><h1>The bigger picture.</h1><p>Accounts, workspaces and subscriptions in one place.</p></div><div className="wt-stats">{[[users, 'Registered users'], [websites, 'Websites'], [subscribers, 'Active paid workspaces'], [total, 'Workspaces']].map(([value, label]) => <div key={label} className="wt-card"><span className="wt-muted">{label}</span><strong>{value}</strong></div>)}</div><div className="wt-section-title"><h2>Workspaces</h2><Link href="/admin/plans">Manage packages →</Link></div><div className="wt-table-wrap"><table className="wt-table"><thead><tr><th>Workspace</th><th>Plan / billing</th><th>Usage</th><th>Access control</th></tr></thead><tbody>{workspaces.map(workspace => <tr key={workspace.id}><td><strong>{workspace.name}</strong><small>{workspace.status.toLowerCase()}</small></td><td>{workspace.billingExempt ? 'Complimentary' : workspace.billingPlan?.name ?? 'No plan'}<small>{workspace.billingStatus}</small></td><td>{workspace._count.projects} websites<br />{workspace._count.members} members</td><td><ActionForm action={manageWorkspace} label="Apply"><input type="hidden" name="id" value={workspace.id} /><select name="operation" aria-label={`Manage ${workspace.name}`}><option value={workspace.status === 'ACTIVE' ? 'suspend' : 'restore'}>{workspace.status === 'ACTIVE' ? 'Suspend workspace' : 'Restore workspace'}</option><option value={workspace.billingExempt ? 'require-plan' : 'exempt'}>{workspace.billingExempt ? 'Require paid plan' : 'Grant complimentary access'}</option></select></ActionForm></td></tr>)}</tbody></table></div><div className="wt-pagination">{page > 1 && <Link href={`/admin?page=${page - 1}`}>← Previous</Link>}<span>Page {page}</span>{page * 20 < total && <Link href={`/admin?page=${page + 1}`}>Next →</Link>}</div><section className="wt-card mt-8"><h2>Recent administration activity</h2>{audit.length ? audit.map(event => <div className="wt-audit" key={event.id}><strong>{event.action}</strong><span>{event.actor?.email ?? 'Stripe / system'}</span><time>{event.createdAt.toLocaleString('en-CA')}</time></div>) : <p className="wt-muted">Changes to accounts and billing appear here.</p>}</section></AppShell>
}
