import Link from 'next/link'
import { prisma } from '@awb/database'
import { requireAdmin } from '@/lib/tenancy'
import { AppShell } from '@/components/account/app-shell'
import { ActionForm } from '@/components/account/action-form'
import { manageUser } from '@/app/actions/admin'
export default async function AdminUsersPage({ searchParams }: { searchParams: Promise<{ q?: string; page?: string }> }) {
  const admin = await requireAdmin(); const query = await searchParams
  const q = String(query.q ?? '').slice(0, 100), page = Math.max(1, Math.min(10000, Number(query.page) || 1))
  const where = q ? { OR: [{ email: { contains: q, mode: 'insensitive' as const } }, { name: { contains: q, mode: 'insensitive' as const } }] } : {}
  const [users, total] = await Promise.all([prisma.user.findMany({ where, orderBy: { createdAt: 'desc' }, skip: (page - 1) * 25, take: 25, select: { id: true, name: true, email: true, emailVerified: true, suspendedAt: true, isPlatformAdmin: true, createdAt: true, _count: { select: { memberships: true } } } }), prisma.user.count({ where })])
  return <AppShell title="User management" active="/admin/users"><div className="wt-heading"><p className="wt-eyebrow">PLATFORM ADMIN</p><h1>Your community, managed.</h1><p>{total} accounts · Permissions are enforced on the server.</p></div><form className="wt-search"><input name="q" defaultValue={q} placeholder="Search names or email addresses" aria-label="Search users" /><button className="wt-button">Search</button></form><div className="wt-table-wrap"><table className="wt-table"><thead><tr><th>User</th><th>Status</th><th>Workspaces</th><th>Access</th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><strong>{user.name ?? 'Unnamed'}</strong><small>{user.email}</small></td><td><span className="wt-badge">{user.suspendedAt ? 'Suspended' : user.emailVerified ? 'Verified' : 'Unverified'}</span>{user.isPlatformAdmin && <small>Platform admin</small>}</td><td>{user._count.memberships}</td><td>{user.id === admin.id ? <span className="wt-muted">Your account</span> : <ActionForm action={manageUser} label="Apply"><input type="hidden" name="id" value={user.id} /><select name="operation" aria-label={`Manage ${user.email}`}><option value={user.suspendedAt ? 'restore' : 'suspend'}>{user.suspendedAt ? 'Restore access' : 'Suspend access'}</option><option value={user.isPlatformAdmin ? 'remove-admin' : 'grant-admin'}>{user.isPlatformAdmin ? 'Remove admin role' : 'Grant admin role'}</option></select></ActionForm>}</td></tr>)}</tbody></table></div><div className="wt-pagination">{page > 1 && <Link href={`/admin/users?q=${encodeURIComponent(q)}&page=${page - 1}`}>← Previous</Link>}<span>Page {page}</span>{page * 25 < total && <Link href={`/admin/users?q=${encodeURIComponent(q)}&page=${page + 1}`}>Next →</Link>}</div></AppShell>
}
